import sales1 from "./images/sales1.png";
import sales2 from "./images/sales2.png";
import sales3 from "./images/sales3.png";
import sales4 from "./images/sales4.png";
import cake3 from "./images/cake3.jfif";
import cake8 from "./images/cake8.jpg";

export const data = [
  {
    id: 1,
    name: "Chocolate Velvet Cake",
    description:
      "Rich and moist chocolate cake layered with cream cheese frosting.",
    price: 600.0,
    image: sales1,
  },
  {
    id: 2,
    name: "Lemon Meringue Tart",
    description: "Tangy lemon curd topped with fluffy meringue.",
    price: 610.0,
    image: sales2,
  },
  {
    id: 3,
    name: "Classic Red Velvet Cake",
    description:
      "Velvety cake with a hint of cocoa, topped with cream cheese frosting.",
    price: 620.0,
    image: sales3,
  },
  {
    id: 4,
    name: "Vanilla Bean Cheesecake",
    description: "Smooth cheesecake infused with real vanilla beans.",
    price: 630.0,
    image: sales4,
  },
  // {
  //   id: 5,
  //   name: "Mango Coconut Mousse",
  //   description: "Light and airy mousse made with fresh mango and coconut.",
  //   price: "¢640.00",
  //   image: sales1,
  // },
  // {
  //   id: 6,
  //   name: "Carrot Cake",
  //   description: "Spiced carrot cake with walnuts and cream cheese frosting.",
  //   price: "¢650.00",
  //   image: sales2,
  // },
  // {
  //   id: 7,
  //   name: "Tiramisu",
  //   description:
  //     "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone.",
  //   price: "¢660.00",
  //   image: sales3,
  // },
  // {
  //   id: 8,
  //   name: "Matcha Green Tea Cake",
  //   description: "Light and fluffy cake infused with matcha green tea.",
  //   price: "¢670.00",
  //   image: sales4,
  // },
  // {
  //   id: 9,
  //   name: "Peanut Butter Chocolate Cake",
  //   description: "Decadent chocolate cake with peanut butter frosting.",
  //   price: "¢680.00",
  //   image: sales1,
  // },
  // {
  //   id: 10,
  //   name: "Black Forest Cake",
  //   description: "Rich chocolate cake layered with cherries and whipped cream.",
  //   price: "¢690.00",
  //   image: sales2,
  // },
  // {
  //   id: 11,
  //   name: "Strawberry Shortcake",
  //   description:
  //     "Fluffy sponge cake layered with fresh strawberries and whipped cream.",
  //   price: "¢700.00",
  //   image: sales3,
  // },
  // {
  //   id: 12,
  //   name: "Cookies and Cream Cake",
  //   description: "Chocolate cake with cookies and cream filling and frosting.",
  //   price: "¢710.00",
  //   image: sales4,
  // },
  // {
  //   id: 13,
  //   name: "Raspberry Almond Tart",
  //   description:
  //     "Almond tart filled with raspberry jam and topped with sliced almonds.",
  //   price: "¢720.00",
  //   image: sales1,
  // },
  // {
  //   id: 14,
  //   name: "Hazelnut Chocolate Torte",
  //   description: "Dense chocolate torte enriched with toasted hazelnuts.",
  //   price: "¢730.00",
  //   image: sales2,
  // },
  // {
  //   id: 15,
  //   name: "Pumpkin Spice Cake",
  //   description:
  //     "Moist pumpkin cake with warm spices and cream cheese frosting.",
  //   price: "¢740.00",
  //   image: sales3,
  // },
  // {
  //   id: 16,
  //   name: "Banana Bread Pudding",
  //   description: "Warm bread pudding made with ripe bananas and vanilla sauce.",
  //   price: "¢750.00",
  //   image: sales4,
  // },
  // {
  //   id: 17,
  //   name: "Chocolate Chip Cookies",
  //   description: "Classic cookies loaded with semi-sweet chocolate chips.",
  //   price: "¢760.00",
  //   image: sales1,
  // },
  // {
  //   id: 18,
  //   name: "Peach Cobbler",
  //   description: "Warm peach filling topped with a buttery biscuit crust.",
  //   price: "¢770.00",
  //   image: sales2,
  // },
  // {
  //   id: 19,
  //   name: "Coconut Cream Pie",
  //   description: "Creamy coconut filling topped with whipped cream.",
  //   price: "¢780.00",
  //   image: sales3,
  // },
  // {
  //   id: 20,
  //   name: "Almond Joy Cake",
  //   description: "Chocolate cake layered with coconut and almonds.",
  //   price: "¢790.00",
  //   image: sales4,
  // },
  // {
  //   id: 21,
  //   name: "Lime Tart",
  //   description: "Zesty lime curd in a buttery tart shell.",
  //   price: "¢800.00",
  //   image: sales1,
  // },
  // {
  //   id: 22,
  //   name: "Cherry Clafoutis",
  //   description: "Baked cherry custard dessert that's simple yet delightful.",
  //   price: "¢810.00",
  //   image: sales2,
  // },
  // {
  //   id: 23,
  //   name: "S'mores Brownies",
  //   description:
  //     "Fudgy brownies topped with marshmallows and graham cracker crumbs.",
  //   price: "¢820.00",
  //   image: sales3,
  // },
  // {
  //   id: 24,
  //   name: "Caramel Flan",
  //   description: "Smooth flan topped with rich caramel sauce.",
  //   price: "¢830.00",
  //   image: sales4,
  // },
  // {
  //   id: 25,
  //   name: "Lemon Lavender Cake",
  //   description: "Fragrant cake with lemon and lavender flavors.",
  //   price: "¢840.00",
  //   image: sales1,
  // },
  // {
  //   id: 26,
  //   name: "Chocolate Mint Cupcakes",
  //   description: "Moist cupcakes with a refreshing mint frosting.",
  //   price: "¢850.00",
  //   image: sales2,
  // },
  // {
  //   id: 27,
  //   name: "Bourbon Pecan Pie",
  //   description: "Classic pecan pie with a touch of bourbon.",
  //   price: "¢860.00",
  //   image: sales3,
  // },
  // {
  //   id: 28,
  //   name: "Nutella Stuffed Cookies",
  //   description: "Soft cookies filled with creamy Nutella.",
  //   price: "¢870.00",
  //   image: sales4,
  // },
  // {
  //   id: 29,
  //   name: "Cinnamon Roll Cake",
  //   description: "Cake version of classic cinnamon rolls with a glaze.",
  //   price: "¢880.00",
  //   image: sales1,
  // },
  // {
  //   id: 30,
  //   name: "Gingerbread Cake",
  //   description: "Spiced gingerbread cake topped with cream cheese frosting.",
  //   price: "¢890.00",
  //   image: sales2,
  // },
  // {
  //   id: 31,
  //   name: "Vanilla Chai Cupcakes",
  //   description: "Cupcakes infused with warm chai spices and vanilla.",
  //   price: "¢900.00",
  //   image: sales3,
  // },
  // {
  //   id: 32,
  //   name: "Chocolate Peanut Butter Pie",
  //   description: "No-bake pie with a chocolate and peanut butter filling.",
  //   price: "¢910.00",
  //   image: sales4,
  // },
  // {
  //   id: 33,
  //   name: "Coconut Lime Cheesecake",
  //   description: "Creamy cheesecake with coconut and lime flavors.",
  //   price: "¢920.00",
  //   image: sales1,
  // },
  // {
  //   id: 34,
  //   name: "Brown Butter Apple Tart",
  //   description: "Tart filled with brown butter apples and spices.",
  //   price: "¢930.00",
  //   image: sales2,
  // },
  // {
  //   id: 35,
  //   name: "Blueberry Muffins",
  //   description: "Fluffy muffins bursting with fresh blueberries.",
  //   price: "¢940.00",
  //   image: sales3,
  // },
  // {
  //   id: 36,
  //   name: "Matcha Tiramisu",
  //   description: "A twist on the classic tiramisu with matcha flavor.",
  //   price: "¢950.00",
  //   image: sales4,
  // },
  // {
  //   id: 37,
  //   name: "Pistachio Cake",
  //   description: "Light cake with ground pistachios and a cream frosting.",
  //   price: "¢960.00",
  //   image: sales1,
  // },
  // {
  //   id: 38,
  //   name: "Caramel Apple Cheesecake",
  //   description: "Cheesecake topped with caramel and apple slices.",
  //   price: "¢970.00",
  //   image: sales2,
  // },
  // {
  //   id: 39,
  //   name: "Mocha Fudge Cake",
  //   description: "Rich chocolate cake with a hint of coffee.",
  //   price: "¢980.00",
  //   image: sales3,
  // },
  // {
  //   id: 40,
  //   name: "Peanut Butter Blondies",
  //   description: "Soft blondies with a peanut butter twist.",
  //   price: "¢990.00",
  //   image: sales4,
  // },
  // {
  //   id: 41,
  //   name: "Spiced Pear Galette",
  //   description: "Rustic galette filled with spiced pears.",
  //   price: "¢1000.00",
  //   image: sales1,
  // },
  // {
  //   id: 42,
  //   name: "Raspberry Chocolate Tart",
  //   description: "Chocolate tart filled with fresh raspberries.",
  //   price: "¢1010.00",
  //   image: sales2,
  // },
  // {
  //   id: 43,
  //   name: "Lavender Honey Cake",
  //   description: "Delicate cake with lavender and honey flavors.",
  //   price: "¢1020.00",
  //   image: sales3,
  // },
  // {
  //   id: 44,
  //   name: "Key Lime Pie",
  //   description: "Tangy key lime pie with a graham cracker crust.",
  //   price: "¢1030.00",
  //   image: sales4,
  // },
  // {
  //   id: 45,
  //   name: "Chocolate Orange Cake",
  //   description: "Moist chocolate cake with a hint of orange zest.",
  //   price: "¢1040.00",
  //   image: sales1,
  // },
  // {
  //   id: 46,
  //   name: "Vanilla Fig Tart",
  //   description: "Tart filled with fresh figs and vanilla custard.",
  //   price: "¢1050.00",
  //   image: sales2,
  // },
  // {
  //   id: 47,
  //   name: "Salted Caramel Brownies",
  //   description: "Fudgy brownies with a swirl of salted caramel.",
  //   price: "¢1060.00",
  //   image: sales3,
  // },
  // {
  //   id: 48,
  //   name: "Coconut Macaroons",
  //   description: "Chewy macaroons made with shredded coconut.",
  //   price: "¢1070.00",
  //   image: sales4,
  // },
  // {
  //   id: 49,
  //   name: "Berry Pavlova",
  //   description: "Crispy meringue topped with fresh berries and whipped cream.",
  //   price: "¢1080.00",
  //   image: sales1,
  // },
  // {
  //   id: 50,
  //   name: "Chocolate Lava Cake",
  //   description: "Warm chocolate cake with a gooey chocolate center.",
  //   price: "¢1090.00",
  //   image: sales2,
  // },
];

export const homeData = [
  {
    id: 201,
    name: "",
    description: "",
    price: "",
  },
];

export const promotionData = [
  {
    id: 101,
    name: "Double chocolate cake",
    price: 300.00,
    image: cake8,
    description: "",
  },
  {
    id: 102,
    name: "Double chocolate cake",
    price: 300.00,
    image: cake3,
    description: "",
  },
];
